### ISSUE TITLE
How to read a variable value with Opal-R

### ISSUE THREAD

**Issue by carlosmontenegrodeveloper1** [obiba/rserver-admin#17]
Hello dear friends.

I have installed R and R-Studio.
So, I can read datasources, tables and variables with this example:
-----------------------------------
# Referencia a librería cliente OPAL
library(opalr)

# https login
o<-opal.login('administrator', '123xxa@@', 'http://localhost:8080')

# Project:
datasource <- 'Harmonization_ics'

# Table:
table <- 'dm_demographic_'

message("**** variables ****")
opal.variables(o, datasource, table)

opal.logout(o)     
-----------------------------------

Now, I need to read the value of each variable. When I try to execute the block of code I get the message:  OPAL url is required.

What do I need to do for reading values and with that error message? 

Thank you in advance,
Carlos
...
![Opal url required](https://user-images.githubusercontent.com/57047653/72476160-1a1c7380-37b2-11ea-96a9-17113bf12845.png)

**Comment by kazoompa** [comment]
Try specifying `url` param name:
```
o<-opal.login('administrator', '123xxa@@', url='http://localhost:8080')
```

See doc:

```
# explicite username/password login

o <- opal.login(username='administrator', password='password', url='https://opal-demo.obiba.org')
opal.logout(o)

# explicite personal access token login
o <- opal.login(token='HYG16LO0VaX4O0UardNbiqmr2ByBpRke', url='https://opal-demo.obiba.org')
opal.logout(o)

# login using options and user credentials
options(opal.username='administrator',
opal.password='password',
opal.url='https://opal-demo.obiba.org')
o <- opal.login()
opal.logout(o)

# login using options and personal access token
options(opal.token='HYG16LO0VaX4O0UardNbiqmr2ByBpRke',
opal.url='https://opal-demo.obiba.org')
o <- opal.login()
opal.logout(o)

# login using ssl key pair
options(opal.opts=list(
  sslcert='my-publickey.pem',
  sslkey='my-privatekey.pem'))
o <- opal.login(url='https://opal-demo.obiba.org')
opal.logout(o)
```

**Comment by carlosmontenegrodeveloper1** [comment]
Hello Kazoompa.
Thank you so much for helping.

Greetings,
Carlos
